# Generated by Django 3.2.8 on 2021-10-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instr_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='featured_image',
        ),
    ]
