# Generated by Django 3.2.8 on 2021-11-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instr_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['created_on'], 'verbose_name': 'ad', 'verbose_name_plural': 'ads'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['title'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='ad',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
    ]
