# Generated by Django 3.2.8 on 2021-11-14 19:32

from django.db import migrations, models
import instr_main.models


class Migration(migrations.Migration):

    dependencies = [
        ('instr_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-created_on'], 'verbose_name': 'ad', 'verbose_name_plural': 'ads'},
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=instr_main.models.user_image_folder),
        ),
    ]
