# Generated by Django 3.2.8 on 2021-10-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instr_main', '0002_auto_20211027_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created_on']},
        ),
    ]
