# Generated by Django 3.2.8 on 2021-11-05 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instr_main', '0002_auto_20211103_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='image_set',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='instr_main.storage_backends.MediaStorage', verbose_name='image')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instr_main.ad')),
            ],
        ),
    ]
