# Generated by Django 3.2.8 on 2021-11-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instr_main', '0002_alter_ad_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
