# Generated by Django 3.2.8 on 2021-10-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instr_main', '0003_auto_20211027_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='geolocation',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='ads',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='geolocation',
        ),
        migrations.AlterField(
            model_name='ad',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
