# Generated by Django 3.2.8 on 2021-10-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instr_main', '0004_auto_20211028_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image_set',
            field=models.ImageField(default='placeholder', upload_to='instr_main.storage_backends.MediaStorage', verbose_name='image'),
        ),
    ]
